src/Document.php
src/Xml.php

Which also means `validate()` can more easily be reused.

XML class should know the schema to use

---

src/Document.php
src/Product.php
tests/ProductsTest.php
tests/fixtures/products.xml

This allows descriptions to be added completely unescaped. For now it's a hack, but longer term we need to allow this to be handled more elegantly.

Allow raw descriptions

---

src/Parser.php

Fixes
```
PHP Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML
```

Validate the element is a proper element before parsing

---

README.md
src/Parser.php

Fixes 'String could not be parsed as XML' exceptions thrown by `SimpleXMLElement->__construct('')`.

Skip empty nodes when parsing XML

---

src/Parser.php
tests/ProductsTest.php
tests/fixtures/bundles.json
tests/fixtures/invalid_products.xml
tests/fixtures/products.json
tests/fixtures/products.xml
tests/fixtures/sets.json
tests/fixtures/variations.json

When parsing attribute values, ‘true’ was being correctly converted to a boolean, but ‘false’ wasn’t. Fixed that and improved tests.

Bug parsing booleans

---

src/Parser.php
tests/fixtures/bundles-simple.json
tests/fixtures/bundles.json
tests/fixtures/products-simple.json
tests/fixtures/products.json
tests/fixtures/sets-simple.json
tests/fixtures/sets.json
tests/fixtures/variations-simple.json
tests/fixtures/variations.json

Casting "false" to bool is always true, use filter_var instead

Fix casting strings to bools

---

src/Product.php
src/Xml.php
tests/ProductsTest.php
tests/fixtures/invalid_products.xml
tests/fixtures/products.xml

Accept text and unencoded HTML (which will be encoded as UTF-8 entities).

Hotfix: XML entity encoding

---

src/Document.php
tests/ProductsTest.php
tests/fixtures/bundles-simple.json
tests/fixtures/bundles.json
tests/fixtures/products-simple.json
tests/fixtures/products.json
tests/fixtures/products.xml
tests/fixtures/sets-simple.json
tests/fixtures/sets.json
tests/fixtures/variations-simple.json
tests/fixtures/variations.json

Long descriptions that start with HTML tags get treated as internal XML fragments and inserted raw. This fix ensures they’re always inserted as elements and the appropriate escaping is applied. 
I've also updated the tests so the whole XML is compared against the fixtures, previously only the structure was being compared, allowing content errors to slip though.

Fix Long Description Escaping Issues

---

src/Document.php
src/Xml.php
tests/ProductsTest.php
tests/XmlTest.php

- Added new `sanitise()` method that removes invalid XML characters (e.g. record separator).
- Invalid characters are replaced with a single space.
- Updated `escape()` to sanitise automatically.
- Ensured raw `long-description` value gets sanitised.
- Updated unit tests to include invalid character.
```PHP Warning:  DOMNode::appendChild(): Document Fragment is empty in php-demandware-xml/src/Document.php on line 95```

Sanitise Invalid XML Characters

---

src/Parser.php
tests/CategoriesTest.php
tests/fixtures/assignments.json
tests/fixtures/assignments.xml

Noticed that `PROD1` was supposed to have two assignments, but the test array was structured such that `CAT1` assignment would be lost.
Have fixed this, but getting an error with `testAssignmentsParser()` now and can’t spot the issue - halp!

Fix for assignments test data

---

xsd/catalog.xsd

Picking up from @maxakropolis. Basically this adds `<xsd:element name="pinterest-enabled-flag" type="xsd:boolean" minOccurs="0" maxOccurs="unbounded" />` to the schema, as this is suddenly appearing production and tripping things up.

Allow PInterest Flag in XML

---

src/Base.php
tests/ProductsTest.php

These changes are as a result of trying to integrate PHP Demandware XML 2.0 into Fusions, which was failing some tests.

Allow null values for start date, sitemap priority and page attributes

---

src/Xml.php

Fixes 
PHP Fatal error:  Uncaught TypeError: Return value of DemandwareXml\Xml::validate() must be of the type boolean, none returned in /vendor/fusionspim/php-demandware-xml/src/Xml.php:56

Add return value to validate()

---

.gitignore
.php_cs
composer.json
composer.lock
src/Base.php
src/Document.php
src/Parser.php
src/Xml.php
src/XmlException.php
tests/AbstractTest.php
tests/CategoriesTest.php
tests/ParserTest.php
tests/ProductsTest.php
tests/VariantsTest.php
tests/XmlTest.php

This is just some prep work before I add some new bits and pieces.

Update to PHPUnit v6 and remove root namespace slash in use statements

---

.gitignore
composer.json
src/Xml.php
tests/CategoriesTest.php
tests/FixtureHelper.php
tests/ParserTest.php
tests/ProductsTest.php
tests/VariantsTest.php
tests/XmlTest.php
tests/fixtures/categories-simple.json
tests/fixtures/categories.json
tests/fixtures/categories.xml

- Added online from/to dates to categories test.
- Restructured product test so it’s easier to understand how each element is built and differs.
- Test invalid sitemap priority.
- Add XML escape testing.
- Fix autoloader and namespace issues.
- Convert abstract class to a trait and only use where applicable.

Improve and spruce up test suite

---

src/Category.php
tests/CategoriesTest.php
tests/fixtures/category-deleted.xml

This allows us to set the mode for a category to `delete`, in the same way we can for products.

Allow categories to be deleted

---

src/Xml.php

Currently unit tests in an application that uses this library are failing when the tests are run in a certain order. This seems to be because `libxml_clear_errors()` is not being called frequently enough.
For instance, a unit test which attempts to catch xml validation issues and expects the following
```
Entity 'bull' not defined\n\tLines: 4\n\nThe document has no document element.\n\tLines: -1
```
will receive
```
Entity 'bull' not defined\n\tLines: 6, 2, 9, 4, 4\n\nchunk is not well balanced\n\tLines: 10, 5, 21, 19\n\nThe document has no document element.\n\tLines: -1
```
if errors have occurred in other tests

Call libxml_clear_errors() before we start capturing further errors

---

src/Base.php
tests/ProductsTest.php

To simplify https://github.com/fusionspim/fusions/pull/8172
The `is_null` checks within this method suggest that it was designed with the possibility of parameters being null.

Fix setSitemap Typehints

---

src/Writer/EntityWriter/ProductXmlWriter.php
tests/Writer/ProductsTest.php
tests/fixtures/products.xml

When dates are cleared they need to be sent out as empty tags, otherwise they are left in Demand-ware.

Output Empty Tags for Online From / To

---

composer.json

As turned out to be confusing rather than useful.

Remove new lines between commands

---

tests/FixtureHelper.php

`phpunit` is showing warnings here
```
PHPUnit 9.5.1 by Sebastian Bergmann and contributors.
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
WWWWWW.W.........................................                 49 / 49 (100%)
Time: 00:00.037, Memory: 6.00 MB
There were 7 warnings:
1) DemandwareXml\Test\Writer\CategoriesTest::test_categories_xml
Passing an argument of type DOMDocument for the $expectedXml parameter is deprecated. Support for this will be removed in PHPUnit 10.
2) DemandwareXml\Test\Writer\CategoriesTest::test_assignments_xml
Passing an argument of type DOMDocument for the $expectedXml parameter is deprecated. Support for this will be removed in PHPUnit 10.
3) …
```

Amend unit tests ready for PHPUnit10

---

pint.json
src/Parser.php
src/Parser/AssignmentNodeParser.php
src/Parser/BundleNodeParser.php
src/Parser/CategoryNodeParser.php
src/Parser/ProductNodeParser.php
src/Parser/SetNodeParser.php
src/Parser/VariationNodeParser.php
src/Writer/Entity/Assignment.php
src/Writer/Entity/Category.php
src/Writer/Entity/CustomAttribute.php
src/Writer/Entity/DeletedAssignment.php
src/Writer/Entity/DeletedCategory.php
src/Writer/Entity/DeletedProduct.php
src/Writer/Entity/Product.php
src/Writer/Entity/Variant.php
src/Writer/EntityWriter/AssignmentXmlWriter.php
src/Writer/EntityWriter/CategoryXmlWriter.php
src/Writer/EntityWriter/CustomAttributeWriter.php
src/Writer/EntityWriter/DeletedAssignmentXmlWriter.php
src/Writer/EntityWriter/DeletedCategoryXmlWriter.php
src/Writer/EntityWriter/DeletedProductXmlWriter.php
src/Writer/EntityWriter/ProductXmlWriter.php
src/Writer/EntityWriter/VariantXmlWriter.php
src/Writer/Xml/NilEmptyWriter.php
src/Writer/Xml/NotEmptyWriter.php
src/Writer/Xml/XmlFormatterException.php
src/XmlException.php

Fixes https://github.com/fusionspim/php-demandware-xml/pull/263

Add pint rule

---

.github/dependabot.yml
.github/workflows/build-and-push-docker-images.yml
.github/workflows/continuous-integration.yml

- Use [documented username](https://github.com/docker/login-action?tab=readme-ov-file#github-container-registry) for logging into GHCR
- Update actions to more recent versions (but let Dependabot do that in the future)

Update action versions and GHCR username

---

src/Writer/Entity/Category.php
src/Writer/Entity/Product.php
tests/Writer/CategoriesTest.php
tests/Writer/ProductsTest.php

Re orders the `setPageAttribute` param, adjusts tests to match.
Also adds a default of null to the keywords param of the Product class.  
Could probably null the other params  as per the Category class?

Reorders set page attributes

---

.github/workflows/continuous-integration.yml
composer.json
composer.lock
docker/php-cli/Dockerfile

Closes https://github.com/fusionspim/php-demandware-xml/issues/278 
- Replaces 8.2 support with 8.4 in composer 
- Ran a composer update too (may be unnecessary) 
- Updated Dockerfile to point at 8.4.1 alpine cli 
- Dropped 8.2 and 8.3 completely from the CI (might not be required, but tis what I've done for now)
- composer-normalize is causing deprecation warnings, which is hopefully going to be sorted with [this](https://github.com/localheinz/diff/pull/73#issuecomment-2501458747) (It's missing a null type)

8.2 support -> 8.4

---

src/Writer/Entity/Category.php
src/Writer/Entity/Product.php

Since the class properties default to `null`, and the method signatures allow `null`, it seems we don't really need to check them when setting? Could be wrong though!

No need to check whether parameters are `null`
